name: JAVA CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
  Build:
      needs: Clone-down
      runs-on: ubuntu-latest
      steps:
        - name: my-step
          run:  ci/build-app.sh
  Test:
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - name: Test
          run:  ci/unit-test-app.sh
  Upload:
      needs: Test
      runs-on: ubuntu-latest
      steps:
        - name: Upload Repo
          uses: actions/upload-artifact@v2
          with:
            name: code
            path: .
        
        
